### ISSUE TITLE
releasing

### ISSUE THREAD

**Issue by marcandre** [guillaumepotier/Parsley.js#1005]
Could we have `master` == `gh-pages`?

I think this implies:
1) Copying the `CNAME` file
2) Adding/converting the annotation task to the `build` gulp task

In my mind, it's not acceptable that switching branches nukes my `node_modules`/`bower_components`.

Do you want to keep the annotated source thing? It's an interesting idea, I just wonder if it's useful for somebody. I don't use it, that's for sure.

**Comment by guillaumepotier** [comment]
Hi,

> In my mind, it's not acceptable that switching branches nukes my node_modules/bower_components.

This is perfectly right, maybe we could avoid that by using deps from a cdn instead of inside node_modules or bower_components.

> Do you want to keep the annotated source thing? It's an interesting idea, I just wonder if it's useful for somebody. I don't use it, that's for sure.

Here are the stats for documentation
![screen shot 2015-10-21 at 11 53 15](https://cloud.githubusercontent.com/assets/496234/10633387/9d06edb6-77ea-11e5-814d-daf762c700d4.png)

We see that annotated sources and tests are not so much saw. Maybe we could drop these :)
What we clearly see is that examples are the most wanted pages and that we could do much better there (jsfiddle examples could be awesome)

We **need** `gh-pages` as this is the only branch Github serves on the web. On `master` it won't work. We should drop not so needed pages, loose requirements on `node_modules/bower_components` to ease branch switching and merging no ? (a `git merge origin master -X theirs` on `gh-pages` does perfectly the job to import all `master` stuff on `gh-pages`)

WDYT?

**Comment by marcandre** [comment]
Good.

Any reason not to import `CNAME` in master, and whenever we release do `git push origin master:gh-pages` and that's it?

For the examples, I had a quick look and the thing I dislike about `jsfiddle`, `codepen` and all is that we need to edit the code on their site, and then modify the ID code on our end. I'd much rather edit the code in our source files. I've [asked a question](http://programmers.stackexchange.com/questions/300498/javascript-playground-with-all-data-in-the-http-request) about that, maybe there's something out there that exists.

**Comment by marcandre** [comment]
Cool, looks like codepen does what I'd like: blog.codepen.io/documentation/api/prefill/

**Comment by guillaumepotier** [comment]
Yes that's interresting. We should open an issue to migrate exemples there in a second time.

Regarding `CNAME` in `master` no particular problem for me. Go for it.

**Comment by marcandre** [comment]
All good now. Annotated code moved to gulp, included in `gulp build`.
