### ISSUE TITLE
"Too much recursion / Maximum call stack size exceeded" error when using in conjunction with lastest Select2

### ISSUE THREAD

**Issue by Hacktivista** [guillaumepotier/Parsley.js#1028]
I don't know if it's a Select2 problem, or a Parsley problem. I couldn't identify the error :(

Here is the simplest fiddle which shows the problem:
http://jsfiddle.net/jew1mg89/

The error is not present using the previous version of Select2 (3.x)

**Comment by marcandre** [comment]
I'd file a bug with `select2`, since `parsley` runs completely first correctly and then `select2` makes the recursive call. If you reverse the order of the calls there is no problem. So `select2` is confused by something that `parsley` does; I don't know what that is and I doubt it's something that's a problem in itself.

**Comment by marcandre** [comment]
Cause explained in #1036
