### ISSUE TITLE
remote-reverse with custom Async Validator

### ISSUE THREAD

**Issue by dobromir-hristov** [guillaumepotier/Parsley.js#1040]
So can we use remote-reverse attribute with our own Async Validator. When I tried, my AsyncValidator did not fire at all. When I removed the -reverse from the data attribute all was working properly. (without it being reversed ofc). 
Example:
Reuse my Email validation for both cases.
```javascript
 Parsley.addAsyncValidator('emailavailable', function (response) {
                console.log(this);
                return response.status === 200;
            }, baseUrl + '/ajax/check-email-available?email={value}', {
                type: 'GET'
            });
```

**Comment by marcandre** [comment]
Indeed, `reverse` is actually a kind of asynch validator, so you can't have both.

You don't seem to actually need your own asynch validator, except maybe because the `baseUrl` can change?

In any case, I don't see a good way to change this, and I personally would like to see less `asynchValidator`; probably best to write your own validator, it's pretty trivial now that you can return a promise.

HTH
