### ISSUE TITLE
A problem with the simple example 

### ISSUE THREAD

**Issue by mbaas2** [guillaumepotier/Parsley.js#1052]
I'm not sure if this is a general problem or only concerns the demo-page, but when you go to http://parsleyjs.org/doc/examples/simple.html and click the "Email"-field, enter "xx" and <Tab> out, Parsley reports the invalid email - but on top it tells "Yay!
Everything seems to be ok :)"

**Comment by marcandre** [comment]
Mmm, I'll look into it, probably an error in the custom code...

**Comment by marcandre** [comment]
Interesting. This is a real issue; the UI depends on the events to do its thing and because of the way events bubble, the code in the example gets run before the UI.
The example code should run and I think the only solution is for the UI to become a privileged citizen, not just a listener to the events fired by parsley.

**Comment by marcandre** [comment]
Fixed and released.
Thanks for reporting this! :smile:

**Comment by mbaas2** [comment]
Trés bien - thanks very much ;-)
