### ISSUE TITLE
classHandler and errorsContainer as functions does not work correctly

### ISSUE THREAD

**Issue by vsn4ik** [guillaumepotier/Parsley.js#1060]
http://parsleyjs.org/doc/annotated-source/defaults.html#section-16
http://parsleyjs.org/doc/annotated-source/defaults.html#section-18

After 3538ae49b6e8888da2f2588035da2ab47c58620a.

Please, go back
1. `this.options.errorsContainer(this)` or
2. `this.options.errorsContainer.call(this)` and update annotated-source.

**Comment by marcandre** [comment]
Oups :bomb: sorry for this.
Fixed & released.
Thanks!

**Comment by marcandre** [comment]
Hi @saveman71 
I'm sorry you got burned by this issue. It is almost 3 years old though.
I try to follow semver, so all `x.y.z` releases are "broken" in some way compared to `x.y.max`. I also typically don't reference bugs in the changelog either, only features. Finally, updating to the latest minor release should always be an improvement and is recommended. In short, I will continue to spend time otherwise, sorry.

**Comment by saveman71** [comment]
Ah, completely missed that they were a lot of more patch releases before 2.4.x, so I assumed wrongly (looking at the changelog) that the next release was 2.4.2. My bad.
