### ISSUE TITLE
Update your docs!! Docs examples broken, more

### ISSUE THREAD

**Issue by Ttante** [guillaumepotier/Parsley.js#1099]
What kind of issue is this? (put 'x' between the square brackets)

 - [ ] Question. This issue tracker is not the place for questions. If you want to ask how to do
       something, or to understand why something isn't working the way you expect it to, use
       http://stackoverflow.com/questions/ask .
       Provide working code, starting from http://codepen.io/marcandre/pen/jqbzyN?editors=101.
       We monitor the tag `parsley.js`.

 - [ x] Bug report. If you’ve found a bug, you must provide a minimal example in a CodePen,
       starting from http://codepen.io/marcandre/pen/jqbzyN?editors=101 .

 - [ ] Feature Request. Make sure there's no good way to do what you want first;
       consider asking on http://stackoverflow.com/questions/ask first.

The docs are a mess!!! It's so hard to find correct usage examples for anything!! The codepen you refer to on this page: http://parsleyjs.org/doc/examples/customvalidator.html  is broken, codepen link here:   http://codepen.io/pen/?editors=1011

Also, the code on that page has issues. It appears the code is from 2.3.3 and since that was written, 
'window.Parsley.addValidator', now fails and requires window.ParsleyValidator.addValidator instead. You guys seem to be changing the usage of this code base too fast for the web to keep up with. Can you please make an effort to catch 2016 up with how to use your library? There is still lots of confusion over the library changes from version 1 to 2, and the fact that lots of v2.3 code is not compatible v2.4 is forcing me to rewrite things that your library is already supposed to include. 

Sorry for the frustration but my team and I have spent way too much time googling how to use your library this year.

**Comment by marcandre** [comment]
Sorry to hear about your frustration.

The CodePens were not working because the assets didn't load, as indicated by the multitude of errors in the console. Looks like the latest tag wasn't pushed properly and `rawgit.com` therefore couldn't load them. Sorry about that, fixed now.

We are indeed moving the API so that there's only one global variable used (`window.Parsley`) and not a multitude like it was. Nevertheless, we try to keep backwards compatibility so your old code should work, even though you will get deprecation notices. If that's not the case, let us know. That's the goal for the whole of the 2.x series; we follow semantic versioning. 

In particular, calls through `window.ParsleyValidator` should work but are deprecated. I believe both the docs and the examples are correct in that regards, but let me know if I'm wrong.

BTW, the best way to improve things is to propose changes, for example with PRs. All the docs and the examples are in the repo.

I think I addressed all your concerns, so I'll close this, but if that's not the case, it's easy to reopen.

Thanks for pointing out CodePens were not working.

**Comment by custa1200** [comment]
Marc-Andre you handled that well, I would have lost it if somebody had written something like that to me. All the work you do is appreciated by most.
