### ISSUE TITLE
Floating number validation

### ISSUE THREAD

**Issue by cgrimal** [guillaumepotier/Parsley.js#1129]
What kind of issue is this? (put 'x' between the square brackets)

 - [ ] Question. This issue tracker is not the place for questions. If you want to ask how to do
       something, or to understand why something isn't working the way you expect it to, use
       http://stackoverflow.com/questions/ask .
       Provide working code, starting from http://codepen.io/marcandre/pen/jqbzyN?editors=101.
       We monitor the tag `parsley.js`.

 - [x] Bug report. If you’ve found a bug, you must provide a minimal example in a CodePen,
       starting from http://codepen.io/marcandre/pen/jqbzyN?editors=101 .

 - [ ] Feature Request. Make sure there's no good way to do what you want first;
       consider asking on http://stackoverflow.com/questions/ask first.

--
I think I found a bug with floating number validation. Here is a CodePen to illustrate it:
http://codepen.io/cgrimal/pen/jApoyO?editors=1010

The `data-parsley-type="number"` is not validating any number input with a `.`
I read the docs, and tried many things but I can't make it work.
One thing that may help you: it works if you use release **2.2.0-rc4** and the problem starts with release **2.2.0**.

I'll use 2.2.0-rc4 for the time being but I'm willing to understand if it is a genuine bug of the lib or me!

Thanks guys,
Clément

**Comment by marcandre** [comment]
Mmm, right, the issue is with the way parameters are passed. If you use `parsley-type-min='0.1'` (since it's the `min` parameter to the `type` validator you want to specify) it'll work as expected.

I'm too jetlagged to think what is the perfect solution to address this in general. If I'm not mistaken, `<input type="text" step="0.1">` is [not valid HTML5](https://html5.validator.nu/), so I'm not sure we should support it.

**Comment by marcandre** [comment]
PS: Thanks for the CodePen :smile:

**Comment by cgrimal** [comment]
Merci @marcandre ! (I'll stick to english even though I think we're both french)

I added the `data-parsley-min="0.1"` attribute to my input but it still doesn't accept any float value. I also remove the `step="0.1"` attribute but I don't understand [the "Number" section of the documentation](http://parsleyjs.org/doc/index.html#psly-validators-list) where it says:
> Validates that a value is a valid number according to the given step, min and original value.

Anyway, that's not my real issue, so probably not worth looking too much into it.

There is no rush so please, take your time to recover from the jet-lag :sunglasses:, I'm happy with 2.2.0-rc4 for now!

**Comment by marcandre** [comment]
It's `data-parsley-type-min`, not `data-parsley-min`

**Comment by marcandre** [comment]
BTW, latest is v2.4.3

**Comment by danhardman** [comment]
Has there been any closure on this issue? I can't seem to validate decimals/floating numbers either.

```html
<input data-parsley-type="number" required type="text" />
```

Results in invalid value errors. I'm using version `2.4.4`

**Comment by marcandre** [comment]
Ok, so here's the deal.

One can use `type="number" step="..."  ...`, with all the caveats. This will be "mapped" so that it behaves as `data-parsley-type="number" data-parsley-type-step="..." ...`

Note the `data-parsley-type-step` attribute here... Indeed, all arguments to `data-parsley-validatornamehere` have form `data-parsley-validatornamehere-heresanargument`.

So it's normal that `<input data-parsley-type="number" required type="text" value="0.1"/>` won't validate, as per spec, even with `step="..."`; the only time where the `step` attribute is looked at is with the automatic mapping of HTML5 attributes ike `type="number"`.

`<input data-parsley-type="number" data-parsley-type-step="0.01" required type="text" value="0.1"/>` or similar will validate.

Does this answer everyone's questions here?

Suggestions, or help with documentation / examples / anything always appreciated

**Comment by danhardman** [comment]
The only thing that needs to happen is when I specify that I want something validated as a number, however parsley wants to a define a number, which as I see it, should be anything that returns `!isNaN(foo) == true`.

I shouldn't be worrying about other specs that aren't part of the parsley library interrupting things.

Would I be able to overwrite a built in validator? I'll just overwrite the `data-parsley-type="number"` validator with:

```js
window.Parsley
  .addValidator('number', {
    requirementType: 'number',
    validateString: function(value) {
      return !isNaN(value);
    },
    messages: {
      en: 'This value should be a number.'
    }
  });
```

**Comment by marcandre** [comment]
@danhardman  Please realize that `"1.e-9"` is a "number", according to your definition, even though for most uses it's would not be acceptable.

Overwriting builtin validators is not supported.

You are free to want to completely ignore HTML5 validators & related specs, but that has not been Parlsey's stance, although we do deviate from the standard from time to time (e.g. `pattern`).

I think that if the default `step` was `'any'` for `data-parsley-type="number"`, it would mostly get out of your way, no?

**Comment by danhardman** [comment]
@marcandre `1.e-9` is a perfectly fine number, I don't see the problem. If I wanted only [0-9] values, I'd use the digits validator or integer.

Would you be able to give an example of where that behaviour wouldn't be desired?

I just find it very confusing that `data-parsley-type="number"` doesn't work for all numbers. There's too many assumptions being made

**Comment by marcandre** [comment]
> Would you be able to give an example of where that behaviour wouldn't be desired?

I'd venture that most numbers entered are prices. I can think of GPAs, lab results in the medical field, etc.

**Comment by danhardman** [comment]
@marcandre The exact reason I'm having this issue is because validation on price values isn't working because it doesn't properly support decimals.

If you don't want to allow decimals in validation, that should be the hoop to jump through, rather than trying to convince parsley that a number is in fact a number.

As I said, if I wanted whole numbers, I'd use `data-parsley-type="digits"` or `data-parsley-type="integer"`. That makes much more sense.

**Comment by marcandre** [comment]
For price values, it is much better to specify `data-parsley-type-step="0.01"`, so `1.23` is a valid price but `1.234` isn't, don't you think?

**Comment by danhardman** [comment]
I validate back-end where it matters and values get treated as 2.d.p. If someone wants to be funny, they can be, it'll only round the value up/down and display the value as it should be.

Point still stands, `1.234` should be considered valid by `data-parsley-type="number"` and if I want to limit to 2.d.p, I should have to do something extra.

**Comment by marcandre** [comment]
So I conclude that you are :+1: on changing the default `step` from `1` to `'any'` in case of `data-parsley-type="number"`. I won't change the default `step` for `<input type=number>` though.

**Comment by danhardman** [comment]
@marcandre Ah, yeah sorry that kinda got lost in everything.

**Comment by marcandre** [comment]
Default changed in `master`, will release soon.
