### ISSUE TITLE
Focusout / Focusin event no being triggered, keyDown instead

### ISSUE THREAD

**Issue by Joramt** [guillaumepotier/Parsley.js#1135]
I'm trying to use parsley to create custom validation on various fields, and i've met some problem with the you of the focusin event ( focusout as well ) 

this is my HTML code  :

` <input type="password" data-parsley-mustmatchpassword='password' data-parsley-required="true" data-parsley-trigger="focusin"  />`

According to the doc, my custom validator mustmatchpassword should be triggered while focusing in a field, so let's try to log a message 

On this example im focused in and no message : 
![one](https://cloud.githubusercontent.com/assets/11468135/18880099/bbbd863a-84a4-11e6-9f64-abd1a861a2ab.png)

On this example, the message has been logged 8 times, every time i pressed a key :
![trhee](https://cloud.githubusercontent.com/assets/11468135/18880185/0e62d282-84a5-11e6-83e6-16c2e2eab3df.png)

On this example, im still focused in and no other message except the 8 previous ones have been logged :
![four](https://cloud.githubusercontent.com/assets/11468135/18880215/25e773ea-84a5-11e6-8c21-5bca11c3fdf1.png)

**Comment by marcandre** [comment]
Hi!

My name is Marc-André and **I'd like your help**. I'm not the original author but I liked the project so much I started contributing more and more; now I'm the (only) maintainer.

#### How you can help

I'd like **you to help me** in keeping the issues of this project organized. In particular, I'd very much like questions to be asked on [Stack Overflow](http://stackoverflow.com)(reasons just down below) and I think **you could help**.

To serve that goal, I wrote that questions should be asked on [Stack Overflow](http://stackoverflow.com) in the [READ ME](https://github.com/noelboss/featherlight#questions) file. Still, some people asked questions here.

I requested the same in the [Contributing Guidelines](https://github.com/noelboss/featherlight/blob/master/.github/CONTRIBUTING.md). Even though GitHub has a paragraph saying "Please review the guidelines for contributing to this repository." that shows up whenever someone creates an issue, some people still asked questions here.

Finally, GitHub allowed us to write a template issue, in which I wrote
> This issue tracker is not the place for questions. If you want to ask how to do
> something, or to understand why something isn't working the way you expect it to, use
> http://stackoverflow.com/questions/ask .
> Provide working code, starting from http://jsfiddle.net/JNsu6/15/.
> We monitor the tag `featherlight.js`.

Still, some people like you delete this text and ask a question here. So my question is: **why did you feel it was the right thing to do**? What could I possibly have done so that this basic wish was respected? I must admit that I feel disrespected whenever someone completely ignores my requests. I understand that most developpers don't feel the urge to help by digging in, inspecting the code and contributing back with great bug reports or pull requests, but it saddens me when people show little care and disregard maintainer wishes.

It would help me a lot if you helped me find a solution so that questions are asked on [Stack Overflow](http://stackoverflow.com).

#### Why StackOverflow?

I feel that [StackOverflow](http://stackoverflow.com) is much better organized for questions and answers than GitHub. Not too surprising, that's exactly what it was designed for!

It has a much better interface to find similar questions, so there's a better chance a question and its answers will help someone else.

I monitor the tag for this project, so I normally will read the question. Sometimes, someone else has already answered the question, which is awesome for whoever wrote the question and for me! That never happens with GitHub issues, btw.

Otherwise I can answer it, especially if it shows what the requester has tried, and has a working example. If something is not clear, there's the comment section, that insure that the discussion doesn't have to be re-read by others that only want the answer.

If the question is badly asked, for example if it has no [working example](http://jsfiddle.net/JNsu6/15/), I can also ignore it and downvote it. Maybe someone will answer it, either way, I don't have an opened issue being stale in GitHub forever.

Indeed, I try as best as I can to keep the list of open GitHub issues down to a minimum. Things there should mostly be things that need to be fixed one way or another. Having a bunch of half baked questions in there would not help at all.

I'm hoping you will reply with good hints on how to achieve this goal. Thanks.

**Comment by Joramt** [comment]
Hi marc,
What a long message, I'll try to be as clear and concise as possible. Not everyone take times to read everything that concern every project, it's a shame i agree with you, but this is how life is. As much as you havent read every terms and conditions everytime one appears in your screen, i havent read all the specification of this project. In fact i believe that me, and perhaps quite a lot of people around here ( you wouldnt have crafted such a sophisticated message for 1 or 2 random dude ) dont read it and focus only on how to achieve what they're looking for, through the docs and example. 
Therefore, some of us ( not many ), will still find bugs in various project, it's normal and it happens everytime, everywhere. Again, some of us ( not many ) will take the necessary time to report this bug, so the maintainer or the author can fix it ! Some of thoses issues report wont necesseraily be nicely written, with concrete example or even screenshoot, some will be false positive or will be a simple misuse of the framework, but they still will take on their time trying to help you ! Thus improving the project, and making a beautiful relationship between the author and the user.

On a second note, im pretty sure if there is an issue category on every repository present on github, there might be a reason ! Maybe the correct solution would be to use this efficiently instead of redirecting people on stack overflow for god knows what reason, so that you can do the exact same thing you wouldve done here ! Oh and you know why its also a good idea to use the issues section ( besides basics semantics ) ? Other people can see if their issues happened before, and if it wasnt a real issue they will know how to address it ! 

That's pretty much why i thought it was the right thing to do, but heh who am i afterall ? Im sorry ive used the issues tab to report something i believed was an issue ( i dont get how you mistook it for a question because there's no " ? " in any of my bug report ) and didnt get the reflex to ask on stack overflow a very specific question about a very specific framework, which should be totally the first thing that should pop in someone mind whenever they report an issue : " Where could i find the largest community of this framework ? On the github project page ? Noooo, stackoverflow !! "

**Comment by marcandre** [comment]
I believe I've explained why I feel SO is a better place for questions. Many other open source projects do the same, btw.

If this is a bug report, could you please provide a working example (as requested in the blurb you deleted when creating this issue), provide clear steps on how to reproduce it and state what should be happening instead. Please also fix your first sentence as error(s) in it prevent it from being understandable.
