### ISSUE TITLE
How to call parsley validation in error produce at server side and can we apply parsley validation on button click not using form submit? 

### ISSUE THREAD

**Issue by khanwasim1992** [guillaumepotier/Parsley.js#1146]
What kind of issue is this? (put 'x' between the square brackets)

 - [ ] Question. This issue tracker is not the place for questions. If you want to ask how to do
       something, or to understand why something isn't working the way you expect it to, use
       http://stackoverflow.com/questions/ask .
       Provide working code, starting from http://codepen.io/marcandre/pen/jqbzyN?editors=101.
       We monitor the tag `parsley.js`.

 - [ ] Bug report. If you’ve found a bug, you must provide a minimal example in a CodePen,
       starting from http://codepen.io/marcandre/pen/jqbzyN?editors=101 .

 - [ ] Feature Request. Make sure there's no good way to do what you want first;
       consider asking on http://stackoverflow.com/questions/ask first.

**Comment by marcandre** [comment]
Hi!

My name is Marc-André and **I'd like your help**. I'm not the original author but I liked the project so much I started contributing more and more; now I'm the (only) maintainer.

#### How you can help

I'd like **you to help me** in keeping the issues of this project organized. In particular, I'd very much like questions to be asked on [Stack Overflow](http://stackoverflow.com)(reasons just down below) and I think **you could help**.

To serve that goal, I wrote that questions should be asked on [Stack Overflow](http://stackoverflow.com) in the [READ ME](https://github.com/noelboss/featherlight#questions) file. Still, some people asked questions here.

I requested the same in the [Contributing Guidelines](https://github.com/noelboss/featherlight/blob/master/.github/CONTRIBUTING.md). Even though GitHub has a paragraph saying "Please review the guidelines for contributing to this repository." that shows up whenever someone creates an issue, some people still asked questions here.

Finally, GitHub allowed us to write a template issue, in which I wrote
> This issue tracker is not the place for questions. If you want to ask how to do
> something, or to understand why something isn't working the way you expect it to, use
> http://stackoverflow.com/questions/ask .
> Provide working code, starting from http://jsfiddle.net/JNsu6/15/.
> We monitor the tag `featherlight.js`.

Still, some people like you delete this text and ask a question here. So my question is: **why did you feel it was the right thing to do**? What could I possibly have done so that this basic wish was respected? I must admit that I feel disrespected whenever someone completely ignores my requests. I understand that most developpers don't feel the urge to help by digging in, inspecting the code and contributing back with great bug reports or pull requests, but it saddens me when people show little care and disregard maintainer wishes.

It would help me a lot if you helped me find a solution so that questions are asked on [Stack Overflow](http://stackoverflow.com).

#### Why StackOverflow?

I feel that [StackOverflow](http://stackoverflow.com) is much better organized for questions and answers than GitHub. Not too surprising, that's exactly what it was designed for!

It has a much better interface to find similar questions, so there's a better chance a question and its answers will help someone else.

I monitor the tag for this project, so I normally will read the question. Sometimes, someone else has already answered the question, which is awesome for whoever wrote the question and for me! That never happens with GitHub issues, btw.

Otherwise I can answer it, especially if it shows what the requester has tried, and has a working example. If something is not clear, there's the comment section, that insure that the discussion doesn't have to be re-read by others that only want the answer.

If the question is badly asked, for example if it has no [working example](http://jsfiddle.net/JNsu6/15/), I can also ignore it and downvote it. Maybe someone will answer it, either way, I don't have an opened issue being stale in GitHub forever.

Indeed, I try as best as I can to keep the list of open GitHub issues down to a minimum. Things there should mostly be things that need to be fixed one way or another. Having a bunch of half baked questions in there would not help at all.

I'm hoping you will reply with good hints on how to achieve this goal. Thanks.
