### ISSUE TITLE
[Feature Request] Add validatorExists() method

### ISSUE THREAD

**Issue by wujekbogdan** [guillaumepotier/Parsley.js#1216]
There's no official way to check if validator exists (we can only use "private" _underscored methods, but this is not a reliable way because they're not a part of the official API). When the `Parsley.addValidator()` method is called and validator already exists, then a `Validator "${validatorName}" is already defined` warning is shown in the console.

So it would be great if there was an additional `Parsley.validatorExists()` method.

**Comment by marcandre** [comment]
Sure, we could do that.
Maybe a better possibility would be to allow adding the same validator multiple times without a warning. I.e. Only warn if the parameters given differ (string comparison) form the current validator.
Am I correct in presuming you get the warning because you're adding a the same validator more than once?

**Comment by wujekbogdan** [comment]
> Am I correct in presuming you get the warning because you're adding a the same validator more than once?

Yes. I'm adding it more than once because I can't check if it was already added. Parsley instance is global, my code has a class that has multiple instances so each instance is trying to initialize Parsley validators.

This is more a cosmetic issue than a real issue. The only thing that's happening are these warnings in the console :)

**Comment by marcandre** [comment]
I added `hasValidator`, since I don't know of an easy way to compare objects in javascript. *sigh*
