### ISSUE TITLE
Parsley does not revalidate Selectize Element

### ISSUE THREAD

**Issue by zanechua** [guillaumepotier/Parsley.js#1278]
What kind of issue is this? (put 'x' between the square brackets)

 - [x] Bug report. If you’ve found a bug, you must provide a minimal example in a CodePen,
       starting from https://codepen.io/zanechua/pen/qQYKZr?editors=101 .

1. Click Validate on the form
2. Select an Option
3. See that Parsley does not revalidate the element to valid

Looked through #1134 but that doesn't seem to be the case

**Comment by marcandre** [comment]
First, *thank you for the codepen*. It makes all the difference in the world.

So the issue is twofold:
* Selectize doesn't handle the `input` event as it should. I [opened an issue](https://github.com/selectize/selectize.js/issues/1462).
* You tried to circumvent this by using `data-parsley-trigger="change"` (I imagine), but you also need to use `data-parsley-trigger-after-failure="change"`. Alternatively you could catch the `change` events and trigger an `input` event (and not need any special triggers). Either solutions will resolve your issue.

**Comment by zanechua** [comment]
@marcandre 

I extended the onChange event from selectize and manually fired the parsley validate for the component which solves my issue. But I didn't know there was a trigger-after-failure option for parsley.

Let me test that out!
