### ISSUE TITLE
When submit button clicked twice group other than specified is validated

### ISSUE THREAD

**Issue by aliemre1990** [guillaumepotier/Parsley.js#1340]
What kind of issue is this? (put 'x' between the square brackets)

 - [ ] Question. This issue tracker is not the place for questions. If you want to ask how to do
       something, or to understand why something isn't working the way you expect it to, use
       http://stackoverflow.com/questions/ask .
       Provide working code, starting from http://codepen.io/marcandre/pen/jqbzyN?editors=101.
       We monitor the tag `parsley.js`.

 - [x] Bug report. If you’ve found a bug, you must provide a minimal example in a CodePen,
       starting from http://codepen.io/marcandre/pen/jqbzyN?editors=101 .

 - [ ] Feature Request. Make sure there's no good way to do what you want first;
       consider asking on http://stackoverflow.com/questions/ask first.

Here is the code example. When i click submit button twice it validates other group too.

https://jsfiddle.net/m68qkspb/13/

**Comment by marcandre** [comment]
Thanks for the bug report. I'm not sure exactly what is going on, but I suspect the issue is that `parsley` is assuming one will not interfere with the submitting control flow. I believe your code interfere's with Parsley's code, and Parsley might be rebinding itself after the first validation and taking over again (hence the validation of both fields).

Please use normal buttons to validate just part of the form. [This example](http://parsleyjs.org/doc/examples/multisteps.html) shows one way to do this.

HTH
