### ISSUE TITLE
data-trigger="focus blur change" doesn't trigger validation

### ISSUE THREAD

**Issue by airtonix** [guillaumepotier/Parsley.js#303]
http://plnkr.co/edit/ELCWZJ?p=preview
1. click in any field
2. click in another field...
##### What happens

no validation occurs
##### What do I expect?

clicking out should at least have the same effect as clicking submit
##### What triggers validation
- changing the field value

**Comment by talofo** [comment]
I don't think this is an issue. It's a UX decision. It makes sense to NOT validate right away. You truly want to validate things on focus out, but only after the user enters something. Otherwise, you will get a bunch of excessive validation messages just for tabbing around, and that is useless information for the user at that time, if the user just decides to tab around to fill in other fields. I hope you DON'T "fix" this. :)
