### ISSUE TITLE
How simply force success validation on hidden field

### ISSUE THREAD

**Issue by dinatih** [guillaumepotier/Parsley.js#616]
Hi! I wonder how to make your exemple code from version 1 works in version 2 :(https://github.com/guillaumepotier/Parsley.js/issues/32)

```
$( '#form' ).parsley( 'addListener', {
    onFieldValidate: function ( elem ) {

        // if field is not visible, do not apply Parsley validation !
        if ( !$( elem ).is( ':visible' ) ) {
            return true;
        }

        return false;
    }
} );
```

It seems to be impossible to make it with version 2, because it doesn't use the return of the callback to pass the validation

**Comment by tiptronic** [comment]
@dinatih: How does that translate to Javascript (as in the question)? (And no - I don't want to learn Coffescript ;))

**Comment by marcandre** [comment]
@tiptronic Just go to http://coffeescript.org/ , click on "Try coffeescript", copy-paste.

**Comment by marcandre** [comment]
In any case, it's probably best to simply add `:hidden` to the exclusion list then to do the suggested solution here.

**Comment by JeroenReumkens** [comment]
@marcandre I'm not sure if the best solution is the add :hidden to the exclusion list. The problemen we've ran into today, is that live validation doesn't work if the field is made visible after for example a checkbox is ticked. This is because Parsley ignores these fields and doesn't bind the change events to it. 

For that reason, I think it is better to use the logic presented above. However, it seems that this does not work in the recent versions anymore. I assume that the solution worked at the time it was posted, therefore I say 'in the recent versions'. Whenever I try to change the validationResult, it is never changed. If I log the validationResult in the next row after I've change it, it will still contain an array of validations instead of 'true'.

**Comment by marcandre** [comment]
@JeroenReumkens Parsley refreshes everything whenever it's asked to check validity (for example on submit). If you need it to refresh at other times (e.g. after showing an element), just call `$('.your-form').isValid()`. Maybe I should expose a `refresh` method or something though.

**Comment by JeroenReumkens** [comment]
@marcandre Thanks for your quick reply. That's indeed the other option to do. However, in this case we have lots of fields and things that toggle visibility of other fields. That would mean we need to implement at at least 10 places the method which would refresh Parsley. That feels a little bit overkill. Therefore I thought it would be a better idea to force the validity to be true if the field is hidden. 

Can you confirm that setting validationResult to true doesn't work anymore?

**Comment by marcandre** [comment]
Mmm, changing `validationResult` works at the form level but indeed doesn't work at the field level (is that what you meant?). It could/should though: #1087

**Comment by JeroenReumkens** [comment]
Yes that is exactly what I mean. If you change the validationResult on field level, that is ignored. 
I hope you are able to fix it. Perhaps I'll have some time next week to take a look myself. Thanks for creating the issue!
