### ISSUE TITLE
errorWrapper and errorClass appended to different location when using custom validator

### ISSUE THREAD

**Issue by KDaigneault** [guillaumepotier/Parsley.js#711]
When using a custom validator the errorWrapper and errorClass are appended to a different element than they are when using a default validator.

Default: 
    .parsley-errors-list appended as sibling of validated element
    .parsley-error is added to validated element
Custom: 
    .parsley-errors-list appended as sibling of validated element's parent
    .parsley-error is added to validated element's parent

See jsfiddle: http://jsfiddle.net/kdaigneault/1ykk4q0x/16/

(Parsley v2.0.3)

**Comment by marcandre** [comment]
First of all, **thank you** for your fiddle.

This is actually the perfect example of *why* every bug should be reported with a fiddle! Without is, I would not have believed you...

The issue is that your validator is called `multiple`. That conflicts with the existing `multiple` option of Parsley... Rename it to something else and you will be good to go.
