### ISSUE TITLE
Move parsley off of jQuery and split ie8, ie7, ie6 browser support split out to separate scripts.

### ISSUE THREAD

**Issue by JemiloII** [guillaumepotier/Parsley.js#830]
With modern javascript, we can remove the dependency of jQuery. We can use the new native search constructors such as querySelector/querySelectorAll. I'm a fan of parsley, just would like to see the jquery clutch removed. Maybe this could be a v3 type of thing.

I'm not saying we cut ie6<ie8 for those who need it, as we can just have those browsers as addon scripts.

**Comment by marcandre** [comment]
I'm not sure you realize the work involved.

Moreover v2.1 uses jQuery events instead of the homegrown pubsub mechanism. This simplifies greatly unbinding and garbage collection for anyone using jQuery to replace elements as jQuery takes care of it automagically.

So I'm afraid this is not the current direction we're heading towards, sorry.
