### ISSUE TITLE
Error message not removed after field removal

### ISSUE THREAD

**Issue by efreibe** [guillaumepotier/Parsley.js#841]
If you validate the form and the validation fails, and if the correction of the data 
includes removal of any form field, that error keeps showing.

This does not have any effect in the validation process, the form submits ok, but the
problem is that if the user has several errors, it causes some confusion.

In my project I have a dynamically created list, the user adds and remove rows,
at the end the list shows a bunch of errors that do not correspond to any offending row.

Here it is a fiddle showing the issue: http://jsfiddle.net/vdye2jg6/2/
To test: click link to remove field, then enter some value in first input field

**Comment by marcandre** [comment]
First, **thank you** for your fiddle.

An easy solution is to wrap your `<input>`s in *any* container you like, and remove that container.

Here's your fiddle (I only wrapped one of the input, I was lazy): http://jsfiddle.net/marcandre/vdye2jg6/3/

OTOH, parsley could clean up the error messages, but I have the impression that most everyone has some wrappers around their input. In particular, do you not have a label for your input?

If you propose a simple PR, it probably would be accepted, but I'm not sure it will get done otherwise...

**Comment by marcandre** [comment]
Note: if ever the error summary feature/plugin of #640 gets done, then it will be necessary to do the cleanup.

**Comment by efreibe** [comment]
Thank you, I've ended changing _bindFields until the bug is solved:

```
_bindFields: function () {
   var oldfields = this.fields;
    ...
   $(oldFields).not(this.fields).each(function() { 
      $.emit('parsley:field:reset', this);
   })
}
```

**Comment by marcandre** [comment]
Actually that looks like a good solution.

**Comment by marcandre** [comment]
Ok, I adapted your code and pushed it to master.
Thanks for your efforts in communicating this issue!

**Comment by guillaumepotier** [comment]
:+1:

**Comment by efreibe** [comment]
You're welcome, I'm glad I could help
