### ISSUE TITLE
Custom validators suppress JS errors

### ISSUE THREAD

**Issue by Rambomst** [guillaumepotier/Parsley.js#867]
Whenever I have a JS error in my custom validation callbacks it just suppresses the error message and then parsley treats the field has valid allowing a form submit.

Is this how it is meant to function or is this an error?

**Comment by marcandre** [comment]
From the `CONTRIBUTING` file which you apparently haven't read:

## Questions?

Please ask questions on [StackOverflow](http://stackoverflow.com/questions/ask) and be sure to include the `parsley.js` tag. Please **provide an example**, starting for example from [this jsfiddle](http://jsfiddle.net/marcandre/58vnaqur/)

## Issues?

If you believe you have found a bug in `parsley`, please **provide an example**, starting for example from [this jsfiddle](http://jsfiddle.net/marcandre/58vnaqur/).

This makes it possible for you to be sure you have isolated the issue to a minimal case. It also makes it much easier for us to understand your issue. Sometimes the issue is [completely different than what you would expect](https://github.com/guillaumepotier/Parsley.js/issues/711) and only an actual example can lead to a solution.

**Comment by Rambomst** [comment]
Loving the condescending first line of your reply.

https://jsfiddle.net/1zqrpq87/3/

**Comment by marcandre** [comment]
Ah, I see, I thought you were referring to `addError`.

Agreed, that should not happen.

Looks like the `validators` library is catching all errors, not just constraint validations.

**Comment by marcandre** [comment]
I'm not super familiar with the `validators` lib, but I've create a PR for @guillaumepotier which I think would resolve the issue.

**Comment by r-polonskiy** [comment]
Oh great, because I faced with this weird behaviour too. And as temporary solution, just to have ability to see errors, I added following strings in "catch ( violation ) { return violation; }" :

        if (violation instanceof Violation) {
          return violation;
        } else {
          console.log(violation);
        }

**Comment by r-polonskiy** [comment]
@marcandre How can I see changes from your PR, for educational purpose?)

**Comment by marcandre** [comment]
@r-polonskiy You click on the PR, click on "commits", and you can see the diff. Or is that not your question?

**Comment by marcandre** [comment]
I'm happy to report that we no longer use the `validator.js` library and that this is no longer an issue...
