### ISSUE TITLE
`required` & `type="number"` at once only shows required error message

### ISSUE THREAD

**Issue by di5abled** [guillaumepotier/Parsley.js#874]
I am using `required` & `type="number"` on one input element, the validation seems to work like expected, but I only see the required error massage, even if some text is provided but isn't numeric.

This is the code I use:
```
<input required="required" data-parsley-errors-container="#form__errors__zip" name="zip" type="number" id="zip">
```

You can finde the jsfiddle here: http://jsfiddle.net/di5abled/jkhLmwk9/

I'm working with verison `2.0.7` insalled via bower.

**Comment by marcandre** [comment]
Yeah, nothing we can do about this unfortunately, as it is [not possible to get the invalid value of a `number` field](http://stackoverflow.com/questions/18852244/how-to-get-the-raw-value-an-input-type-number-field).

You could change the `type` and use `data-parsley-type="number"` instead, but then a full keypad would show on mobile & tablets :-(

Doc should be improved though, so I'll keep this opened if you don't mind.

**Comment by di5abled** [comment]
oh damn, thats a reason...
too bad, maybe I could use `type="tel"`. I'll have a look.

yeah keep it open, I have no problem with that.

**Comment by thetiby** [comment]
Here's what I suggest: fix the browser `input[type=number]` by resetting the value with the value computed by the browser like so: http://jsfiddle.net/jkhLmwk9/4/

This way, we don't need an invalidation message for number type inputs; either there is a valid number there, or there isn't, and we require it.

Since the `input` event [isn't supported all the way to old browsers](https://developer.mozilla.org/en-US/docs/Web/Events/input#Browser_compatibility), the keyboard events could be used for that case, making sure to treat the pasting via mouse as well. (could be done with a right click listener and a timeout)

**Comment by marcandre** [comment]
Good points, although  the reset is a bit crude, since a typo erases all info.

The type="number" definitely needs more doc, maybe a wiki page.

**Comment by thetiby** [comment]
how about something like this then? http://jsfiddle.net/jkhLmwk9/8/
1 typo is allowed, user is informed about his/her mistake

**Comment by marcandre** [comment]
I've updated the doc, clearer wording always welcome.
