### ISSUE TITLE
Parsley Init does not fire properly

### ISSUE THREAD

**Issue by ryanchuleff** [guillaumepotier/Parsley.js#962]
version 2.2.0-rc1

The 'form:event' and 'field:event' triggers don't fire in the Parsley code.

line 1114:
```
// Internal only.
// Shortcut to trigger an event
// Returns true iff event is not interrupted and default not prevented.
_trigger: function (eventName) {
  eventName = 'form:' + eventName;
  return this.trigger.apply(this, arguments);
}
```
line 1387:
```
// Internal only.
// Shortcut to trigger an event
_trigger: function (eventName) {
  eventName = 'field:' + eventName;
  return this.trigger.apply(this, arguments);
}
```

In the code above, `eventName` comes into the method with a value of 'init', therefore `arguments` is an array containing a single value: `['init']`.  On the first line of the method, we prefix the `eventName` to include form or field. But then we pass in the original and un-changed `arguments` to the trigger method.  As a result, the `setupForm` and `setupField` methods are never triggered.

Changing the code as reflected below was enough to resolve the issue in my testing.  Without this change, the Form is never properly instantiated.

```
// Internal only.
// Shortcut to trigger an event
_trigger: function (eventName) {
  eventName = 'field:' + eventName;
  return this.trigger.apply(this, [eventName]);
}
```

**Comment by marcandre** [comment]
It's not very well known, but... http://stackoverflow.com/a/3242548/8279

Note that `_trigger` accepts more than one argument, but there's no good way in ES3 to express that. We will be transitionning to ES6, so this code will be much clearer.

I'll close this, but please open a different issue stating what your actual issue is :smile:

**Comment by marcandre** [comment]
Oops, I'm reading in a comment that this has been removed in script mode... is it possible you're running in script mode somehow?

**Comment by ryanchuleff** [comment]
I assume you mean 'strict mode'?  I'm not familiar with 'script mode'.  i'll take a look at my code to see if strict mode was applied.

**Comment by marcandre** [comment]
lol, yeah, that's what I meant to write, sorry :smile:

Anyways, turns out you're right and `_trigger` is now never called with more than 1 arguments, so I simplified the code.

There were two other places where I changed the code to avoid incompatibilities with non-strict mode our test suite now runs fine in strict mode.

Let me know if I've missed something. Thanks!

**Comment by ryanchuleff** [comment]
Thanks Marc, much appreciated!

On Mon, Aug 24, 2015 at 7:29 PM, Marc-André Lafortune <
notifications@github.com> wrote:

> lol, yeah, that's what I meant to write, sorry [image: :smile:]
>
> Anyways, turns out you're right and _trigger is now never called with
> more than 1 arguments, so I simplified the code.
>
> There were two other places where I changed the code to avoid
> incompatibilities with non-strict mode our test suite now runs fine in
> strict mode.
>
> Let me know if I've missed something. Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/guillaumepotier/Parsley.js/issues/962#issuecomment-134413109>
> .
>



-- 
Ryan Yanchuleff
----------------------------------------------
em: ryan@yanchuleff.com
ph:  703.587.4958
