### ISSUE TITLE
[Feature request] input[type="file"]

### ISSUE THREAD

**Issue by wujekbogdan** [guillaumepotier/Parsley.js#989]
Is there any chance to implement file input validation using FormData()? It's supported by all major browsers (and IE>=10): http://caniuse.com/#search=FormData

**Comment by marcandre** [comment]
Ok, IIC, you want to add a `remote` validation to an input of type=file, and that won't work currently because our ajax call uses something like `data: {input_name: input_value}`, right?

So I think it would be nice to support type=file too. Since we aim to support IE8/9 too, we should issue a warning in those cases, and continue using the basic data form unless it's a file.

Any chance you'd be able to provide a PR for this?

**Comment by wujekbogdan** [comment]
No, not a remote validator. Regular front-end validation using [FormData()](https://developer.mozilla.org/pl/docs/Web/API/FormData )

I know that FormData works only in modern browsers, and there's no reasonable polyfill for IE<10. So maybe it would be better to deliver it as a plugin (an additional validator) not as a core feature?

**Comment by marcandre** [comment]
I'm glad to report that it is easy to validate this in 2.2, since the arguments passed to the validators are: `value`, `requirement`, `parsleyInstance`. From the parsley instance, you have access to `$element`.

**Comment by wujekbogdan** [comment]
Thank you. I was using an older version.

Thanks to this feature I was able to create a code sample for basic `file[type=input]` validation:
https://jsfiddle.net/02vjbLrs/14/

**Comment by marcandre** [comment]
I've added this to our [custom validator example](http://parsleyjs.org/doc/examples/customvalidator.html)
