### ISSUE TITLE
'step' attribute is not validating in number fields

### ISSUE THREAD

**Issue by plauclair** [guillaumepotier/Parsley.js#992]
On number fields, the 'step' attribute is not validating.

For example, any precision of a float will work even though the precision is specified, e.g. step=0.01, val=0.0001 validates.

Also, for integers, step 5 would validate even if the value is 7.

I would suggest, if you add this feature, that when min attribute is missing, that the base for validation be 0, and otherwise the base be a mix of min + exact multiples of the step value.

Thanks a lot for this awesome library!

**Comment by marcandre** [comment]
I feel it can't be enforced on `step` attribute, since browser allow (as per spec I imagine) a user to type in a value that's not a multiple of `step`.

We could have a `parsley-step` attribute though, or something similar, that would enforce it. Care to write a PR?

**Comment by plauclair** [comment]
I might squeeze in a little time within the next few weeks but don't take my word for it, I have too many other implementations on my plate right now unfortunately.

**Comment by marcandre** [comment]
The latest `2.2.0` will accept a `parsley-type="number" parsley-type-step="0.01"` validation following HTML5 specs. I believe this fixes your request, let me know if that's not the case.

**Comment by katywings** [comment]
Will `pasley-type-step` anytime be noted in the docs? Because it's a bit problematic when `parsley-type="number"` is by default checking for integers, the html5 step attribute for floats only working with `type="number"` - which on its own is problematic with chrome browsers (they tend to format float numbers with `,`)

Most users (for float) need to use: `type="text" data-parsley-type-step="0.01" data-parsley-type="number"`, don't they?

**Comment by marcandre** [comment]
Currently, `pasley-type-step` is ignored completely in all cases.

I might be wrong, but my impression was that the spec was using a `.` and not a `,` for decimals. Is Chrome not following it (presumably depending on the computer's locale)? If so, maybe we simply need to tweak our regex for `type = "number"`?
